### ISSUE TITLE
smbr loss training

### ISSUE THREAD

**Issue by liuming5467** [datemoon/tf-code-acoustics#1]
请问一下 训练smbr-loss的话 我看到需要提供一个pdf-id到phone-id的输入 我看到这个是由输入一个（ali， pdf， phone）得到的，请问这个是在kaldi中哪里生成的呢？

**Comment by datemoon** [comment]
你好，这个文件3行组成，第一行是ali所有的id，第二行对应的pdfid，第三行是phoneid，每一行第一个是key，ali手动生成，pdf-id用kaldi，ali-to-pdf，phoneid用ali-to-phone，然后cat到一起就ok

**Comment by datemoon** [comment]
你好，这个文件3行组成，第一行是ali所有的id，第二行对应的pdfid，第三行是phoneid，每一行第一个是key，ali手动生成，pdf-id用kaldi，ali-to-pdf，phoneid用ali-to-phone，然后cat到一起就ok

**Comment by datemoon** [comment]
你好，这个文件3行组成，第一行是ali所有的id，第二行对应的pdfid，第三行是phoneid，每一行第一个是key，ali手动生成，pdf-id用kaldi，ali-to-pdf，phoneid用ali-to-phone，然后cat到一起就ok

**Comment by datemoon** [comment]
你好，这个文件3行组成，第一行是ali所有的id，第二行对应的pdfid，第三行是phoneid，每一行第一个是key，ali手动生成，pdf-id用kaldi，ali-to-pdf，phoneid用ali-to-phone，然后cat到一起就ok
